version: '3'

services:
  db-prod:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PROD_PORT}:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'hemnet-tracker-prod'

  db-dev:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_DEV_PORT}:5432
    volumes:
      - hemnet-tracker-db-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'hemnet-tracker-dev'

volumes:
  hemnet-tracker-db-dev:
